// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEGTIR8ashEuJxy-meo4PBJ0mG6XoUS0A',
    appId: '1:119505937989:web:e824fbcd3d89597997a52c',
    messagingSenderId: '119505937989',
    projectId: 'kueue-1636',
    authDomain: 'kueue-1636.firebaseapp.com',
    storageBucket: 'kueue-1636.appspot.com',
    measurementId: 'G-LT4L2BFQ9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5peTZky4jxF9lxSJYUxb3BVzrim0NyWs',
    appId: '1:119505937989:android:63be814869c8988797a52c',
    messagingSenderId: '119505937989',
    projectId: 'kueue-1636',
    storageBucket: 'kueue-1636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-xGVI5SV5A-LkcoOoe_ioIVxLfF_LhQY',
    appId: '1:119505937989:ios:ce6b70f83e93659797a52c',
    messagingSenderId: '119505937989',
    projectId: 'kueue-1636',
    storageBucket: 'kueue-1636.appspot.com',
    iosClientId: '119505937989-75540g1539egr6ns6ei4st9feptlp9r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.kueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-xGVI5SV5A-LkcoOoe_ioIVxLfF_LhQY',
    appId: '1:119505937989:ios:3da0bbade04db5c897a52c',
    messagingSenderId: '119505937989',
    projectId: 'kueue-1636',
    storageBucket: 'kueue-1636.appspot.com',
    iosClientId: '119505937989-ufkgmliheq68f4qa4t9hlakgqcmrjm9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.kueue.RunnerTests',
  );
}
